[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Full"

opacity = 0.95
blur = true

option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font Mono"
normal.style = "Medium"
bold.family = "FiraCode Nerd Font Mono"
bold.style = "SemiBold"


size = 12