[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Full"

opacity = 0.75
blur = true

option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font Mono"

size = 14